spring:
  application:
    name: urs-dao
  profiles:
    active: dev
  cache:
    type: redis

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.nju.urs.dao.mysql.model.po
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

