spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urs?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/urs
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=10m

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.nju.urs.dao.mysql.model.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl